import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createProvider, credentials, normalizeGames, launchUrl} from '../provider.mjs';
test('missing credentials fail closed',async()=>{assert.equal(credentials({}),false);await assert.rejects(createProvider({env:{}}).catalog(),{status:503});});
test('catalog retains live and slot titles and preserves explicit demo capability',()=>{const games=normalizeGames([{id_hash:'x',name:'Slot',game_type:'slots',play_for_fun_supported:true,provider:'test'},{id_hash:'y',name:'Live',game_type:'live',play_for_fun_supported:false},{id_hash:'z',name:'Unknown'}]);assert.deepEqual(games.map(g=>g.id),['x','y','z']);assert.deepEqual(games.map(g=>g.demoSupported),[true,false,false]);assert.equal(games[1].category,'live');});
test('launch URL rejects script and insecure URLs',()=>{assert.throws(()=>launchUrl('javascript:alert(1)'));assert.throws(()=>launchUrl('http://example.com'));assert.throws(()=>launchUrl('https://user:pass@example.com'));assert.equal(launchUrl('https://example.com/demo'),'https://example.com/demo');});
test('launch requests only a catalog-approved demo and never real money',async()=>{const calls=[];const env={SOFTAGGREGATOR_API_LOGIN:'test-login',SOFTAGGREGATOR_API_PASSWORD:'test-password'};const adapter=createProvider({env,request:async(url,options)=>{const body=JSON.parse(options.body);calls.push(body);return {ok:true,json:async()=>({error:0,response:body.method==='getGameList'?[{id_hash:'provider/one',name:'One',play_for_fun_supported:true}]:body.method==='getGameDemo'?'https://example.com/demo':{}})};}});await assert.rejects(adapter.launch('unlisted'),{status:404});assert.equal(await adapter.launch('provider/one','mobile','https://mongolz.example'),'https://example.com/demo');assert.deepEqual(calls.map(x=>x.method),['getGameList','createPlayer','getGameDemo']);assert.equal(calls[2].gameid,'provider/one');assert.equal(calls[2].device,'mobile');assert.equal(calls[2].play_for_fun,true);assert.equal(calls[2].lang,'en');assert.equal(calls[2].user_username,calls[1].user_username);});
test('upstream failures do not expose credentials',async()=>{const adapter=createProvider({env:{SOFTAGGREGATOR_API_LOGIN:'secret',SOFTAGGREGATOR_API_PASSWORD:'secret'},request:async()=>({ok:true,json:async()=>({error:2,message:'secret'})})});await assert.rejects(adapter.catalog(),e=>e.message==='Provider refused request');});

test('unsupported live games cannot launch as demo',async()=>{const adapter=createProvider({env:{SOFTAGGREGATOR_API_LOGIN:'x',SOFTAGGREGATOR_API_PASSWORD:'y'},request:async()=>({ok:true,json:async()=>({error:0,response:[{id_hash:'live/one',name:'Live',game_type:'live',play_for_fun_supported:false}]})})});await assert.rejects(adapter.launch('live/one'),{status:404});});
