'use client';
import { useEffect, useRef, useState } from 'react';
import type { GameMeta } from '@/lib/games';

type Props={game:GameMeta;lang:'mn'|'en';balance:number;settle:(game:string,bet:number,result:number)=>void};
const rand=(n:number)=>Math.floor(Math.random()*n);
const clamp=(n:number,a:number,b:number)=>Math.min(b,Math.max(a,n));
const MAX_WIN:Record<string,string>={slot:'500×',roulette:'36×',blackjack:'2.5×',baccarat:'9×',plinko:'25×',mines:'10.89×',dice:'19.8×',crash:'100×'};

export default function DemoGame({game,lang,balance,settle}:Props){
 const [bet,setBet]=useState(100); const [message,setMessage]=useState('');
 const [state,setState]=useState<any>({});
 const name=lang==='mn'?game.mn:game.en;
 useEffect(()=>{setMessage('');setState({});},[game.id,game.mn]);
 const roundLocked=state.status==='playing'||state.playing||state.running;
 const canBet=Number.isFinite(bet)&&bet>=10&&bet<=10000&&bet<=balance;
 const win=(mult:number,msg:string)=>{ if(!canBet)return setMessage(lang==='mn'?'Demo үлдэгдэл хүрэлцэхгүй.':'Not enough demo balance.'); const payout=Math.round(bet*mult*100)/100; settle(name,bet,payout-bet);setMessage(`${msg} • ${mult.toFixed(2)}x`);};
 const lose=(msg:string)=>{if(!canBet)return setMessage(lang==='mn'?'Demo үлдэгдэл хүрэлцэхгүй.':'Not enough demo balance.');settle(name,bet,-bet);setMessage(msg);};
 return <div className="demoGame"><div className="gameModalHead"><div><span className="eyebrow">MONGOLZ DEMO ENGINE</span><h2>{game.icon} {name}</h2><span className="maxPotential">MAX WIN <b>{MAX_WIN[game.id]||'—'}</b></span></div><div className="modalBalance"><span>{lang==='mn'?'Үлдэгдэл':'Balance'}</span><b>₮ {balance.toLocaleString()}</b></div></div>
 <div className="betBar"><label>{lang==='mn'?'Бооцоо':'Bet'}<input type="number" value={bet} disabled={Boolean(roundLocked)} min={10} max={10000} step={10} onChange={e=>setBet(clamp(Number(e.target.value)||10,10,10000))}/></label><button disabled={Boolean(roundLocked)} onClick={()=>setBet(Math.max(10,Math.floor(bet/2)))}>½</button><button disabled={Boolean(roundLocked)} onClick={()=>setBet(Math.min(10000,bet*2))}>2×</button><button disabled={Boolean(roundLocked)} onClick={()=>setBet(Math.max(10,Math.min(10000,Math.floor(balance))))}>MAX</button></div>
 {!canBet&&!roundLocked&&<div className="resultBanner" role="status">{lang==='mn'?'Бооцоо 10–10,000 ₮ бөгөөд demo үлдэгдлээс хэтрэхгүй байна.':'Bet must be 10–10,000 and within your demo balance.'}</div>}<div className={"gameBoard"+(!canBet&&!roundLocked?" cannotBet":"")}>{game.id==='slot'&&<Slot win={win} lose={lose} state={state} setState={setState} lang={lang}/>} {game.id==='roulette'&&<Roulette win={win} lose={lose} state={state} setState={setState} lang={lang}/>} {game.id==='blackjack'&&<Blackjack bet={bet} canBet={canBet} settle={settle} name={name} state={state} setState={setState} lang={lang}/>} {game.id==='baccarat'&&<Baccarat win={win} lose={lose} state={state} setState={setState} lang={lang}/>} {game.id==='plinko'&&<Plinko win={win} state={state} setState={setState} lang={lang}/>} {game.id==='mines'&&<Mines bet={bet} canBet={canBet} settle={settle} name={name} state={state} setState={setState} lang={lang}/>} {game.id==='dice'&&<Dice win={win} lose={lose} state={state} setState={setState} lang={lang}/>} {game.id==='crash'&&<Crash bet={bet} canBet={canBet} settle={settle} name={name} state={state} setState={setState} lang={lang}/>}</div>
 {message&&<div className="resultBanner">{message}</div>}<p className="fairNote">{lang==='mn'?'Demo RNG нь Math.random ашигладаг. Мөнгөний тоглоомд ашиглах зориулалтгүй.':'Demo RNG uses Math.random and is not suitable for real-money gaming.'}</p></div>
}

function Slot({win,lose,state,setState,lang}:any){const symbols=['🐎','🦅','💎','🏔️','☀️','👑'];function spin(){const r=[symbols[rand(6)],symbols[rand(6)],symbols[rand(6)]];setState({r});if(r.every((x:string)=>x==='👑'))win(500,lang==='mn'?'MAX WIN!':'MAX WIN!');else if(r[0]===r[1]&&r[1]===r[2])win(25,lang==='mn'?'Жакпот!':'Jackpot!');else if(r[0]===r[1]||r[1]===r[2]||r[0]===r[2])win(2,lang==='mn'?'Хос таарлаа':'Pair');else lose(lang==='mn'?'Дараагийн эргэлтэд амжилт!':'Try the next spin');}return <div className="slotGame"><div className="reels">{(state.r||['🐎','💎','👑']).map((x:string,i:number)=><div key={i}>{x}</div>)}</div><button className="gameAction" onClick={spin}>{lang==='mn'?'ЭРГҮҮЛЭХ':'SPIN'}</button></div>}
function Roulette({win,lose,state,setState,lang}:any){const [pick,setPick]=useState<'red'|'black'|'number'>('red');const [num,setNum]=useState(7);function spin(){const n=rand(37);const red=[1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36].includes(n);setState({n,color:n===0?'green':red?'red':'black'});if(pick==='number'&&num===n)win(36,`${lang==='mn'?'Тоо таарлаа':'Number hit'} ${n}`);else if((pick==='red'&&red)||(pick==='black'&&n!==0&&!red))win(2,`${n}`);else lose(`${lang==='mn'?'Буусан тоо':'Result'}: ${n}`)}return <div><div className={`rouletteWheel ${state.color||''}`}><b>{state.n??'?'}</b></div><div className="choiceRow"><button className={pick==='red'?'selected redPick':''} onClick={()=>setPick('red')}>RED</button><button className={pick==='black'?'selected':''} onClick={()=>setPick('black')}>BLACK</button><button className={pick==='number'?'selected':''} onClick={()=>setPick('number')}>NUMBER</button>{pick==='number'&&<input type="number" min="0" max="36" value={num} onChange={e=>setNum(clamp(+e.target.value,0,36))}/>}</div><button className="gameAction" onClick={spin}>{lang==='mn'?'ЭРГҮҮЛЭХ':'SPIN'}</button></div>}
const deck=()=>{const ranks=[2,3,4,5,6,7,8,9,10,10,10,10,11];return ranks[rand(ranks.length)]};
function handValue(a:number[]){let s=a.reduce((x,y)=>x+y,0);while(s>21&&a.includes(11)){const i=a.indexOf(11);a=[...a];a[i]=1;s=a.reduce((x,y)=>x+y,0)}return s}
function Blackjack({bet,canBet,settle,name,state,setState,lang}:any){function deal(){if(!canBet)return;setState({player:[deck(),deck()],dealer:[deck(),deck()],status:'playing',stake:bet})}function finish(p:number[],d:number[]){let dv=handValue(d);while(dv<17){d=[...d,deck()];dv=handValue(d)}const pv=handValue(p);const stake=state.stake;const playerNatural=pv===21&&p.length===2,dealerNatural=dv===21&&d.length===2;let result=-stake;if(playerNatural&&!dealerNatural)result=stake*1.5;else if(playerNatural&&dealerNatural)result=0;else if(!dealerNatural&&pv<=21&&(dv>21||pv>dv))result=stake;else if(!dealerNatural&&pv===dv)result=0;settle(name,stake,result);setState({player:p,dealer:d,status:'done'});}function hit(){const p=[...(state.player||[]),deck()];if(handValue(p)>21){settle(name,state.stake,-state.stake);setState({...state,player:p,status:'done'})}else setState({...state,player:p})}return <div><div className="cardsArea"><p>Dealer</p><div>{(state.dealer||[]).map((c:number,i:number)=><span className="card" key={i}>{state.status==='playing'&&i===1?'?':c}</span>)}</div><p>{lang==='mn'?'Тоглогч':'Player'} • {handValue(state.player||[])||0}</p><div>{(state.player||[]).map((c:number,i:number)=><span className="card" key={i}>{c}</span>)}</div></div>{state.status!=='playing'?<button className="gameAction" onClick={deal}>{lang==='mn'?'ШИНЭ ГАР':'DEAL'}</button>:<div className="choiceRow"><button onClick={hit}>HIT</button><button onClick={()=>finish(state.player,state.dealer)}>STAND</button></div>}</div>}
function Baccarat({win,lose,state,setState,lang}:any){const [pick,setPick]=useState('banker');function go(){const p=(rand(10)+rand(10))%10,b=(rand(10)+rand(10))%10;setState({p,b});const actual=p===b?'tie':p>b?'player':'banker';if(pick===actual)win(actual==='tie'?9:actual==='banker'?1.95:2,`${actual.toUpperCase()} ${p}:${b}`);else if(actual==='tie'&&pick!=='tie')win(1,`${lang==='mn'?'Тэнцсэн':'Push'} ${p}:${b}`);else lose(`${actual.toUpperCase()} ${p}:${b}`)}return <div><div className="scoreDuel"><div><span>PLAYER</span><b>{state.p??'-'}</b></div><i>VS</i><div><span>BANKER</span><b>{state.b??'-'}</b></div></div><div className="choiceRow">{['player','banker','tie'].map(x=><button className={pick===x?'selected':''} key={x} onClick={()=>setPick(x)}>{x.toUpperCase()}</button>)}</div><button className="gameAction" onClick={go}>{lang==='mn'?'ӨГӨХ':'DEAL'}</button></div>}
function Plinko({win,state,setState,lang}:any){const mult=[25,8,2,1.2,.35,1.2,2,8,25];function drop(){const slot=rand(mult.length);setState({slot});win(mult[slot],`${lang==='mn'?'Үржүүлэгч':'Multiplier'} ${mult[slot]}x`)}return <div><div className="plinkoBoard">{Array.from({length:6}).map((_,r)=><div key={r} className="pegRow">{Array.from({length:r+3}).map((_,i)=><i key={i}/>)}</div>)}<div className="plinkoSlots">{mult.map((m,i)=><span className={state.slot===i?'hit':''} key={i}>{m}x</span>)}</div></div><button className="gameAction" onClick={drop}>{lang==='mn'?'БӨМБӨГ УНАГАХ':'DROP'}</button></div>}
function Mines({bet,canBet,settle,name,state,setState,lang}:any){const start=()=>{if(!canBet)return;const mines=new Set<number>();while(mines.size<4)mines.add(rand(16));setState({mines:[...mines],opened:[],playing:true,stake:bet})};function open(i:number){if(!state.playing||state.opened?.includes(i))return;if(state.mines.includes(i)){settle(name,state.stake,-state.stake);setState({...state,opened:[...state.opened,i],playing:false,bust:i})}else setState({...state,opened:[...state.opened,i]})}function cash(){const n=state.opened?.length||0;if(!n)return;const mult=Math.pow(1.22,n);settle(name,state.stake,state.stake*mult-state.stake);setState({...state,playing:false,cash:true})}return <div><div className="minesGrid">{Array.from({length:16}).map((_,i)=><button key={i} onClick={()=>open(i)} className={state.opened?.includes(i)?(state.mines?.includes(i)?'mine':'gem'):''}>{state.opened?.includes(i)?(state.mines?.includes(i)?'💥':'💎'):'?'}</button>)}</div>{!state.playing?<button className="gameAction" onClick={start}>{lang==='mn'?'ШИНЭ ТОГЛООМ':'NEW GAME'}</button>:<button className="gameAction" onClick={cash}>{lang==='mn'?'АВАХ':'CASH OUT'} • {Math.pow(1.22,state.opened?.length||0).toFixed(2)}x</button>}</div>}
function Dice({win,lose,state,setState,lang}:any){const [target,setTarget]=useState(50);const [dir,setDir]=useState<'under'|'over'>('under');function roll(){const n=Math.random()*100;setState({n});const ok=dir==='under'?n<target:n>target;const chance=dir==='under'?target:100-target;if(ok)win(99/Math.max(chance,1),`${n.toFixed(2)}`);else lose(`${n.toFixed(2)}`)}return <div><div className="diceNumber">{state.n==null?'--':state.n.toFixed(2)}</div><input className="range" type="range" min="5" max="95" value={target} onChange={e=>setTarget(+e.target.value)}/><div className="choiceRow"><button className={dir==='under'?'selected':''} onClick={()=>setDir('under')}>UNDER {target}</button><button className={dir==='over'?'selected':''} onClick={()=>setDir('over')}>OVER {target}</button></div><button className="gameAction" onClick={roll}>{lang==='mn'?'ШОО ХАЯХ':'ROLL'}</button></div>}
function Crash({bet,canBet,settle,name,state,setState,lang}:any){
 const [running,setRunning]=useState(false);const [mult,setMult]=useState(1);
 const round=useRef({value:1,limit:2,stake:0,done:true});
 useEffect(()=>{
  if(!running)return;
  const timer=setInterval(()=>{
   const r=round.current;if(r.done)return;
   r.value=+(r.value+.05).toFixed(2);
   if(r.value>=r.limit){r.done=true;clearInterval(timer);setMult(r.limit);setRunning(false);setState({crashed:r.limit,running:false});settle(name,r.stake,-r.stake)}else setMult(r.value);
  },90);
  return()=>clearInterval(timer);
 },[running]);
 function start(){if(!canBet||!round.current.done)return;const r=Math.max(.0001,Math.random());round.current={value:1,limit:Math.min(100,+(1/Math.pow(r,.58)).toFixed(2)),stake:bet,done:false};setMult(1);setState({running:true});setRunning(true)}
 function cash(){const r=round.current;if(r.done)return;r.done=true;setRunning(false);setState({cash:r.value,running:false});settle(name,r.stake,r.stake*r.value-r.stake)}
 return <div><div className={`crashGraph ${state.crashed?'busted':''}`}><span className="rocket">🚀</span><b>{mult.toFixed(2)}x</b><i/></div>{running?<button className="gameAction cash" onClick={cash}>{lang==='mn'?'АВАХ':'CASH OUT'} {mult.toFixed(2)}x</button>:<button className="gameAction" onClick={start}>{lang==='mn'?'ЭХЛҮҮЛЭХ':'START ROUND'}</button>}</div>
}
