import { publicDemos } from './providers.js';
import { START_BALANCE, randomInt, validateBet, settle, RED, rouletteMultiplier, diceMultiplier, slotMultiplier, mineMultiplier, blackjackScore, blackjackMultiplier, shuffledDeck } from './engine.js';
const $ = s => document.querySelector(s);
const dict = {
 mn: {lobby:'Тоглоомын танхим', originals:'Mongolz Originals', favorites:'Дуртай тоглоом', history:'Тоглолтын түүх', wallet:'Хэтэвч', help:'Тусламж', responsible:'Хариуцлагатай тоглолт', search:'Тоглоом хайх…', deposit:'Цэнэглэх', demo:'DEMO · ВИРТУАЛ КРЕДИТ', eyebrow:'ӨӨРИЙН ХЭМНЭЛЭЭР ТОГЛО', hero:'Аз жаргалын<br>шинэ <em>түвшин.</em>', intro:'Монгол сэтгэл. Дэлхийн мэдрэмж. Өөрийн дуртай тоглоомуудаа нэг дор, үнэгүй туршаарай.', play:'Тоглож эхлэх', explore:'Тоглоом үзэх', all:'Бүгд', slots:'Слот', table:'Ширээний', instant:'Шуурхай', title:'Таны дараагийн дуртай тоглоом', subtitle:'Зүгээр үзэх биш. Шууд тогло.', featured:'ОНЦЛОХ', games:'ТОГЛООМ', credit:'DEMO КРЕДИТ', free:'ҮНЭГҮЙ', unlimited:'ТУРШИХ БОЛОМЖ', playDemo:'Demo тоглох', footer:'Зөвхөн виртуал кредитээр тоглох demo. Бодит мөнгө, шагнал, мөнгөн таталт байхгүй.', bet:'Бооцооны кредит', action:'Тоглох', close:'Хаах', balance:'Үлдэгдэл', noResults:'Тоглоом олдсонгүй.', noHistory:'Тоглолтын түүх хараахан байхгүй.', win:'Хожлоо', loss:'Дахин оролдоорой', push:'Тэнцлээ', invalid:'1–1,000 бүхэл кредит оруулна уу. Үлдэгдлээс хэтрэхгүй.', reset:'Demo кредит сэргээх', resetDone:'10,000 demo кредит сэргээгдлээ.', paymentTitle:'Demo хэтэвч', paymentNote:'Энэ хувилбарт төлбөр авахгүй. Картын мэдээлэл болон crypto бүү илгээгээрэй.', paymentDisabled:'Бодит гүйлгээ холбогдоогүй', virtual:'Виртуал кредит нэмэх', amount:'Кредитийн хэмжээ', added:'Demo кредит нэмэгдлээ', cashout:'Кредит авах', hit:'Карт авах', stand:'Зогсох', start:'Эхлэх', safe:'Аюулгүй', mine:'Мина таарлаа', limit:'Өдрийн алдагдлын хязгаар', save:'Хадгалах', saved:'Тохиргоо хадгалагдлаа', pause:'24 цаг завсарлах', paused:'Тоглолт түр зогссон.', emptyFav:'♡ дарж дуртай тоглоомоо нэмээрэй.', stake:'Бооцоо', payout:'Буцаан авсан', date:'Огноо', game:'Тоглоом', rules:'Дүрэм', freeLabel:'FREE PLAY', more:'Бүх тоглоом', supportText:'Mongolz бол үнэгүй demo. Тоглолт болон үлдэгдэл энэ төхөөрөмжийн browser-д хадгалагдана. Тоглоомын дүрмийг тоглоом бүрийн цонхноос үзээрэй.', settingNote:'Хязгаар нь энэ browser дахь demo тоглолтод үйлчилнэ. Завсарлагыг хугацаанаас нь өмнө цуцлах боломжгүй.', resetConfirm:'Үлдэгдлийг 10,000 болгох уу? Тоглолтын түүх хадгалагдана.', playing:'Тоглож байна…', dealer:'Дилер', you:'Таны карт', red:'Улаан', black:'Хар', zero:'Тэг', under:'Үүнээс бага гарвал хожно', locked:'Нээлттэй тоглолтоо эхлээд дуусгана уу.', dailyLimit:'Өдрийн алдагдлын хязгаарт хүрсэн.', casino:'КАЗИНО', welcome:'Тавтай морил, тоглогч', local:'ТӨХӨӨРӨМЖИД ХАДГАЛАГДАНА', fair:'Тоглолт бүр шинэ боломж', fairText:'6 өөр тоглоом. Өөрийн сонголт. Нэг хэтэвч.', verified:'Үнэгүй demo', depositTab:'Нэмэх', withdrawTab:'Татах', withdrawNote:'Виртуал кредитийг мөнгө болгон татах боломжгүй.', confirmPause:'Demo тоглолтыг 24 цаг завсарлах уу?', rulesTitle:'Тоглоомын дүрэм'},
 en: {lobby:'Game lobby',originals:'Mongolz Originals',favorites:'Favorites',history:'Play history',wallet:'Wallet',help:'Help center',responsible:'Responsible play',search:'Search games…',deposit:'Add credits',demo:'DEMO · VIRTUAL CREDITS',eyebrow:'PLAY ON YOUR OWN TERMS',hero:'Your next<br>level of <em>play.</em>',intro:'Mongolian soul. Global energy. Discover your favorite games in one place, completely free.',play:'Start playing',explore:'Explore games',all:'All games',slots:'Slots',table:'Table games',instant:'Instant games',title:'Meet your next favorite',subtitle:'More than a look. Make your move.',featured:'FEATURED',games:'GAMES',credit:'DEMO CREDITS',free:'FREE',unlimited:'WAYS TO PLAY',playDemo:'Play demo',footer:'Virtual-credit demo only. No real money, prizes, or cash withdrawals.',bet:'Bet credits',action:'Play',close:'Close',balance:'Balance',noResults:'No games found.',noHistory:'No plays yet.',win:'You won',loss:'Try again',push:'Push',invalid:'Enter 1–1,000 whole credits, within your balance.',reset:'Reset demo credits',resetDone:'10,000 demo credits restored.',paymentTitle:'Demo wallet',paymentNote:'Payments are not connected. Do not send card details or crypto.',paymentDisabled:'Live transactions unavailable',virtual:'Add virtual credits',amount:'Credit amount',added:'Demo credits added',cashout:'Collect credits',hit:'Hit',stand:'Stand',start:'Start',safe:'Safe',mine:'Mine hit',limit:'Daily loss limit',save:'Save',saved:'Settings saved',pause:'Take a 24-hour break',paused:'Play is paused.',emptyFav:'Tap ♡ to save a favorite.',stake:'Stake',payout:'Returned',date:'Date',game:'Game',rules:'Rules',freeLabel:'FREE PLAY',more:'All games',supportText:'Mongolz is a free demo. Your balance and play history are stored in this browser on this device. See each game’s rules in its game window.',settingNote:'Limits apply to demo play in this browser. A break cannot be canceled early.',resetConfirm:'Reset balance to 10,000? Play history is kept.',playing:'Playing…',dealer:'Dealer',you:'Your hand',red:'Red',black:'Black',zero:'Zero',under:'Win by rolling under this number',locked:'Finish your current game first.',dailyLimit:'Daily loss limit reached.',casino:'CASINO',welcome:'Welcome, player',local:'SAVED ON THIS DEVICE',fair:'Every play. A new possibility.',fairText:'Six games. Your choice. One wallet.',verified:'Free-play demo',depositTab:'Deposit',withdrawTab:'Withdraw',withdrawNote:'Virtual credits cannot be withdrawn as money.',confirmPause:'Pause demo play for 24 hours?',rulesTitle:'Game rules'}
};
Object.assign(dict.mn,{providers:'Provider demo',providerCount:'Provider',prev:'Өмнөх',next:'Дараах',loadingMore:'Тоглоом',providerTitle:'Жинхэнэ provider. Жинхэнэ тоглоом.',providerNote:'Албан ёсны demo нь provider-ийн сайт дээр шинэ цонхонд нээгдэнэ. Mongolz кредитэд нөлөөлөхгүй.',officialDemo:'Албан ёсны demo',embedded:'Сайт доторх demo',connecting:'Provider каталог ачаалж байна…',needsKeys:'Сайт дотор тоглуулах холболтод SoftAggregator API эрх шаардлагатай.',unavailable:'Provider холболт одоогоор боломжгүй.',providerRules:'Тоглоомын хэл, дүрэм, demo үлдэгдлийг provider удирдана. MN интерфэйс нь Mongolz хэсэгт үйлчилнэ.'});
Object.assign(dict.en,{providers:'Provider demos',providerCount:'Provider',prev:'Previous',next:'Next',loadingMore:'Games',providerTitle:'Real providers. Real games.',providerNote:'Official demos open on the provider’s website in a new tab. They do not use your Mongolz credits.',officialDemo:'Official demo',embedded:'In-site demos',connecting:'Loading provider catalog…',needsKeys:'In-site game launches need SoftAggregator API credentials.',unavailable:'Provider connection is unavailable.',providerRules:'Game language, rules, and demo balance are controlled by the provider. MN translation covers the Mongolz interface.'});
const games=[
 {id:'slots',name:'Golden Steppe',mn:'Алтан тал',cat:'slots',icon:'✦',art:'slot-art',tag:'POPULAR',desc:'3 reels · 5 symbols',rules:{mn:'3 ижил тэмдэг: 8×, 3 алмааз: 20×, хос: 1.5×. Үржүүлэгч нь анхны бооцоог багтаана.',en:'Three matching symbols pay 8×; three diamonds 20×; any pair 1.5×. Multipliers include the stake.'}},
 {id:'roulette',name:'Royal Roulette',mn:'Хааны хүрд',cat:'table',icon:'◉',art:'roulette-art',tag:'CLASSIC',desc:'European · Single zero',rules:{mn:'Улаан/хар: 2×, тэг: 36×. 0–36 дугаартай европ хүрд.',en:'Red/black pays 2×, zero pays 36×. European wheel with numbers 0–36.'}},
 {id:'blackjack',name:'Midnight 21',mn:'Шөнийн 21',cat:'table',icon:'♠',art:'card-art',tag:'STRATEGY',desc:'Hit · Stand · 21',rules:{mn:'21-ээс хэтрэлгүй дилерээс өндөр оноо ав. Хожил 2×, тэнцээ 1×. Дилер soft 17 дээр зогсоно. Natural bonus, split, double байхгүй.',en:'Beat the dealer without exceeding 21. Win pays 2×, push 1×. Dealer stands on soft 17. No natural bonus, split, or double.'}},
 {id:'mines',name:'Crystal Mines',mn:'Болор эрдэнэ',cat:'instant',icon:'◆',art:'mine-art',tag:'ORIGINAL',desc:'25 tiles · 3 mines',rules:{mn:'25 нүдэнд 3 мина бий. Аюулгүй нүд нээх бүрд үржүүлэгч өснө. Минад хүрэхээс өмнө кредитээ аваарай.',en:'25 tiles hide 3 mines. Each safe tile increases the multiplier. Collect before hitting a mine.'}},
 {id:'dice',name:'Lucky Dice',mn:'Азын шоо',cat:'instant',icon:'⚄',art:'dice-art',tag:'QUICK PLAY',desc:'Choose your probability',rules:{mn:'0–99 тоо сонгосон босгоос бага бол хожно. Босго 10–90; үржүүлэгч 0.97 × 100 / босго.',en:'Roll 0–99 below your threshold to win. Choose 10–90; multiplier = 0.97 × 100 / threshold.'}},
 {id:'crash',name:'Sky High',mn:'Тэнгэрийн нислэг',cat:'instant',icon:'↗',art:'crash-art',tag:'ORIGINAL',desc:'Climb · Collect · Repeat',rules:{mn:'Өсөж буй үржүүлэгчийг унахаас өмнө зогсоож кредитээ аваарай. Уналт 1.00×-аас эхэлж болно. 20× хүрвэл автоматаар авна. Энэ нь local demo юм.',en:'Collect at the rising multiplier before it crashes. Crashes can occur at 1.00×. Auto-collect at 20×. This is a local demo.'}}
];
const defaultState=()=>({lang:'mn',balance:START_BALANCE,history:[],favorites:[],limit:2000,pauseUntil:0});
let state=defaultState();try{const s=JSON.parse(localStorage.getItem('mongolz-v1'));if(s&&Number.isFinite(s.balance)&&s.balance>=0){state={...state,...s,lang:s.lang==='en'?'en':'mn',history:Array.isArray(s.history)?s.history.slice(0,100):[],favorites:Array.isArray(s.favorites)?s.favorites.filter(id=>games.some(g=>g.id===id)):[],limit:Number.isFinite(s.limit)&&s.limit>=1?s.limit:2000,pauseUntil:Number.isFinite(s.pauseUntil)?s.pauseUntil:0};}}catch{}
let page='lobby',category='all',query='',active=null,round=null,timer=null,busy=false;
const t=k=>dict[state.lang][k]||k;
const fmt=n=>Number(n).toLocaleString(state.lang==='mn'?'mn-MN':'en-US',{maximumFractionDigits:2});
const persist=()=>{try{localStorage.setItem('mongolz-v1',JSON.stringify(state));}catch{toast(state.lang==='mn'?'Хадгалах боломжгүй.':'Storage unavailable.');}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function logo(){return `<span class="logo-icon">M</span><span class="wordmark">MONGOLZ<span>PLAY BEYOND ORDINARY</span></span>`;}
function render(){document.documentElement.lang=state.lang;$('#app').innerHTML=`
 <aside class="sidebar"><a class="brand" href="#">${logo()}</a><div class="side-label">${t('casino')}</div><nav>${[['lobby','▦'],['providers','◈'],['originals','✦'],['favorites','♡'],['history','◷'],['wallet','▣']].map(([k,i])=>`<button class="nav-item ${page===k?'selected':''}" data-page="${k}"><span>${i}</span>${t(k)}${k==='originals'?'<small>6</small>':''}</button>`).join('')}</nav><div class="side-promo"><span class="promo-star">✧</span><strong>${t('fair')}</strong><p>${t('fairText')}</p><button data-page="originals">${t('explore')} ↗</button></div><div class="side-bottom"><button data-page="responsible">◈ ${t('responsible')}</button><button data-page="help">ⓘ ${t('help')}</button><div class="age">18+ <span>${t('verified')}</span></div></div></aside>
 <div class="main-shell"><header><button class="mobile-logo" data-page="lobby">M<span>MONGOLZ</span></button><div class="header-caption">${t('welcome')} <span>✦</span></div><div class="header-actions"><button class="language" id="language" aria-label="Change language">${state.lang==='mn'?'MN':'EN'} <span>⌄</span></button><button class="balance" data-page="wallet"><span class="coin">✦</span><b>${fmt(state.balance)}</b><small>CR</small></button><button class="primary small" data-page="wallet">＋ ${t('deposit')}</button><span class="avatar">M</span></div></header><main id="content"></main><footer><div class="footer-brand">${logo()}</div><p>${t('footer')}</p><div class="payment-logos"><b>VISA</b><b>●●</b><span>₮ USDT</span><span>₿ BTC</span><span>Ξ ETH</span><small>UI PREVIEW ONLY</small></div></footer><nav class="mobile-nav">${[['lobby','▦'],['providers','◈'],['wallet','▣'],['history','◷']].map(([k,i])=>`<button data-page="${k}" class="${page===k?'selected':''}">${i}<small>${t(k)}</small></button>`).join('')}</nav></div>`;
 $('#language').onclick=()=>{if(busy)return toast(t('locked'));state.lang=state.lang==='mn'?'en':'mn';persist();render();};
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{if(busy)return toast(t('locked'));page=b.dataset.page;query='';category='all';render();});
 if(['lobby','originals','favorites'].includes(page))renderLobby();else if(page==='providers')renderProviders();else if(page==='wallet')renderWallet();else if(page==='history')renderHistory();else renderInfo();
}
function renderLobby(){const c=$('#content');c.innerHTML=`${page==='lobby'?`<section class="hero"><div class="hero-copy"><div class="eyebrow"><span></span>${t('eyebrow')}</div><h1>${t('hero')}</h1><p>${t('intro')}</p><div class="hero-buttons"><button class="primary" id="hero-play">${t('play')} <span>↗</span></button><button class="outline" id="explore">${t('explore')}</button></div><div class="hero-note"><span>✦</span>${t('demo')}</div></div><div class="hero-art" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="floating-star">✦</div><div class="big-card back-card">♦<span>♦</span></div><div class="big-card front-card">A<span>♠</span><i>A</i></div><div class="chip chip-one">M<span>1000</span></div><div class="chip chip-two">M</div><div class="art-caption">THE SPIRIT OF PLAY <span>EST. 2026</span></div></div></section><section class="stats"><div><span>◈</span><strong>06<small>${t('games')}</small></strong></div><div><span>✦</span><strong>10,000<small>${t('credit')}</small></strong></div><div><span>◎</span><strong>MN / EN<small>LANGUAGE</small></strong></div><div><span>∞</span><strong>${t('free')}<small>${t('unlimited')}</small></strong></div></section>`:''}<section class="game-section" id="games"><div class="section-heading"><div><div class="eyebrow muted">MONGOLZ ORIGINALS</div><h2>${page==='favorites'?t('favorites'):t('title')}</h2><p>${t('subtitle')}</p></div><label class="search">⌕ <input id="search" placeholder="${t('search')}" value="${esc(query)}" aria-label="${t('search')}"><kbd>⌘ K</kbd></label></div><div class="filters">${['all','slots','table','instant'].map((k,i)=>`<button data-filter="${k}" class="${category===k?'active':''}">${['▦','✦','♠','ϟ'][i]} ${t(k)}</button>`).join('')}<span class="filter-note">● ${t('freeLabel')}</span></div><div class="game-grid" id="game-grid"></div></section><section class="bottom-banner"><span>✧</span><div><h3>${t('fair')}</h3><p>${t('fairText')}</p></div><button class="outline" data-info>${t('responsible')} ↗</button></section>`;
 if($('#hero-play'))$('#hero-play').onclick=()=>{page='providers';render();};if($('#explore'))$('#explore').onclick=()=>$('#games').scrollIntoView({behavior:'smooth'});
 $('#search').oninput=e=>{query=e.target.value;renderGrid();};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{category=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderGrid();});$('[data-info]').onclick=()=>{page='responsible';render();};renderGrid();if(page==='lobby'){const section=document.createElement('section');section.className='provider-section';section.innerHTML=publicProviderMarkup();$('#games').before(section);bindPublicProviders();}
}
function renderGrid(){const filtered=games.filter(g=>(page!=='favorites'||state.favorites.includes(g.id))&&(category==='all'||g.cat===category)&&(g.name+' '+g.mn).toLowerCase().includes(query.toLowerCase()));$('#game-grid').innerHTML=filtered.length?filtered.map(g=>`<article class="game-card"><div class="game-art ${g.art}"><span class="game-tag">${g.tag}</span><button class="favorite ${state.favorites.includes(g.id)?'saved':''}" data-fav="${g.id}" aria-label="${t('favorites')}: ${g.name}">${state.favorites.includes(g.id)?'♥':'♡'}</button><div class="art-symbol">${g.icon}</div><div class="art-title">${g.name.split(' ').map(w=>`<span>${w}</span>`).join('')}</div><button class="play-overlay" data-game="${g.id}">▶ ${t('playDemo')}</button></div><div class="game-meta"><div><h3>${state.lang==='mn'?g.mn:g.name}</h3><p>MONGOLZ ORIGINALS</p></div><button data-game="${g.id}" aria-label="${t('playDemo')}: ${g.name}">↗</button></div></article>`).join(''):`<div class="empty">${page==='favorites'?t('emptyFav'):t('noResults')}</div>`;document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game));document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{const id=b.dataset.fav;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];persist();renderGrid();});}
function renderWallet(){ $('#content').innerHTML=`<div class="page-heading"><div class="eyebrow">CASHIER</div><h1>${t('paymentTitle')}</h1><p>${t('demo')}</p></div><div class="wallet-layout"><section class="panel wallet-summary"><span class="coin large">✦</span><p>${t('balance')}</p><h2>${fmt(state.balance)} <small>CR</small></h2><span class="status-pill">${t('local')}</span><button class="outline" id="reset">${t('reset')}</button></section><section class="panel"><div class="wallet-tabs"><button class="active" id="deposit-tab">${t('depositTab')}</button><button id="withdraw-tab">${t('withdrawTab')}</button></div><div id="cashier-body"></div></section></div>`;$('#reset').onclick=()=>{if(confirm(t('resetConfirm'))){state.balance=START_BALANCE;persist();render();toast(t('resetDone'));}};const deposit=()=>{ $('#deposit-tab').classList.add('active');$('#withdraw-tab').classList.remove('active');$('#cashier-body').innerHTML=`<p class="notice">ⓘ ${t('paymentNote')}</p><div class="payment-methods">${['VISA / Mastercard','₮ USDT / USDC','₿ Bitcoin','Ξ Ethereum'].map(m=>`<div><b>${m}</b><small>${t('paymentDisabled')}</small></div>`).join('')}</div><form id="credit-form"><label>${t('amount')}<input type="number" id="credit-amount" min="1" max="10000" step="1" value="1000" required></label><button class="primary">＋ ${t('virtual')}</button></form>`;$('#credit-form').onsubmit=e=>{e.preventDefault();const amount=Number($('#credit-amount').value);if(!Number.isInteger(amount)||amount<1||amount>10000)return;state.balance=Math.min(1000000,state.balance+amount);persist();renderWallet();renderBalance();toast(t('added'));};};$('#deposit-tab').onclick=deposit;$('#withdraw-tab').onclick=()=>{$('#withdraw-tab').classList.add('active');$('#deposit-tab').classList.remove('active');$('#cashier-body').innerHTML=`<p class="notice">${t('withdrawNote')}</p><div class="payment-methods">${['Visa / Mastercard','USDT / USDC / BTC / ETH'].map(m=>`<div><b>${m}</b><small>${t('paymentDisabled')}</small></div>`).join('')}</div>`;};deposit();}
function renderHistory(){$('#content').innerHTML=`<div class="page-heading"><div class="eyebrow">YOUR ACTIVITY</div><h1>${t('history')}</h1><p>${t('local')}</p></div><section class="panel table-wrap">${state.history.length?`<table><thead><tr>${['date','game','stake','payout'].map(k=>`<th>${t(k)}</th>`).join('')}</tr></thead><tbody>${state.history.map(h=>`<tr><td>${esc(new Date(h.date).toLocaleString(state.lang==='mn'?'mn-MN':'en-US'))}</td><td>${esc(games.find(g=>g.id===h.game)?.name||h.game)}</td><td>${fmt(h.bet)} CR</td><td class="${h.payout>=h.bet?'positive':'negative'}">${fmt(h.payout)} CR</td></tr>`).join('')}</tbody></table>`:`<div class="empty">${t('noHistory')}</div>`}</section>`;}
function renderInfo(){ $('#content').innerHTML=`<div class="page-heading"><div class="eyebrow">MONGOLZ CARE</div><h1>${t(page)}</h1></div><section class="panel info-panel">${page==='help'?`<h2>${t('verified')}</h2><p>${t('supportText')}</p><p>${t('paymentNote')}</p><p>${t('footer')}</p>`:`<h2>18+ · ${t('responsible')}</h2><p>${t('settingNote')}</p><form id="limit-form"><label>${t('limit')} (CR)<input id="limit" type="number" min="1" max="100000" step="1" required value="${state.limit}"></label><button class="primary">${t('save')}</button></form><button class="outline" id="pause">${t('pause')}</button>${state.pauseUntil>Date.now()?`<p class="notice">${t('paused')} ${new Date(state.pauseUntil).toLocaleString()}</p>`:''}`}</section>`;if($('#limit-form')){$('#limit-form').onsubmit=e=>{e.preventDefault();const l=Number($('#limit').value);if(Number.isInteger(l)&&l>=1&&l<=100000){state.limit=l;persist();toast(t('saved'));}};$('#pause').onclick=()=>{if(state.pauseUntil>Date.now())return toast(t('paused'));if(confirm(t('confirmPause'))){state.pauseUntil=Date.now()+86400000;persist();renderInfo();}};}}
function renderBalance(){const b=$('.balance b');if(b)b.textContent=fmt(state.balance);}
function allowed(bet){if(state.pauseUntil>Date.now()){toast(t('paused'));return false;}const today=new Date().toISOString().slice(0,10);const loss=state.history.filter(h=>h.date.slice(0,10)===today).reduce((s,h)=>s+Math.max(0,h.bet-h.payout),0);if(loss+bet>state.limit){toast(t('dailyLimit'));return false;}if(!validateBet(bet,state.balance)){toast(t('invalid'));return false;}return true;}
function openGame(id){active=games.find(g=>g.id===id);round=null;busy=false;const d=$('#modal');d.innerHTML=`<div class="modal-head"><div><span class="eyebrow">MONGOLZ ORIGINALS · DEMO</span><h2>${state.lang==='mn'?active.mn:active.name}</h2></div><button id="close-modal" aria-label="${t('close')}">×</button></div><div class="game-stage ${active.art}" id="stage"></div><div class="game-controls"><label>${t('bet')}<input id="bet" type="number" min="1" max="1000" step="1" value="100"></label><div id="extras"></div><button class="primary" id="play">${t('action')} ↗</button></div><div class="result" id="result" aria-live="polite">${t('demo')} · ${fmt(state.balance)} CR</div><details><summary>${t('rulesTitle')}</summary><p>${active.rules[state.lang]}</p></details>`;
 $('#close-modal').onclick=()=>{if(busy)return toast(t('locked'));d.close();};d.oncancel=e=>{if(busy){e.preventDefault();toast(t('locked'));}};d.showModal();initialStage();$('#play').onclick=playRound;
}
function initialStage(){ const stage=$('#stage'),extra=$('#extras');if(active.id==='slots')stage.innerHTML='<div class="reels"><span>✦</span><span>💎</span><span>✦</span></div>';if(active.id==='roulette'){stage.innerHTML='<div class="roulette-wheel"><span id="roulette-number">?</span></div>';extra.innerHTML=`<select id="choice" aria-label="Roulette bet"><option value="red">${t('red')} · 2×</option><option value="black">${t('black')} · 2×</option><option value="zero">${t('zero')} · 36×</option></select>`;}if(active.id==='dice'){stage.innerHTML='<div class="dice-number" id="dice-number">50</div>';extra.innerHTML=`<label>${t('under')}<input type="range" id="threshold" min="10" max="90" value="50"><span id="threshold-label">50 · 1.94×</span></label>`;$('#threshold').oninput=e=>$('#threshold-label').textContent=`${e.target.value} · ${(97/Number(e.target.value)).toFixed(2)}×`;}if(active.id==='blackjack')stage.innerHTML=`<div class="hand-label">${t('dealer')}</div><div class="hand"><div class="playing-card card-back">M</div><div class="playing-card card-back">M</div></div><div class="hand-label">${t('you')}</div><div class="hand"><div class="playing-card">A♠</div><div class="playing-card red-card">K♥</div></div>`;if(active.id==='mines')stage.innerHTML=`<div class="mine-grid">${Array.from({length:25},(_,i)=>`<button data-tile="${i}" disabled>◆</button>`).join('')}</div>`;if(active.id==='crash')stage.innerHTML='<div class="crash-visual"><span>↗</span><strong id="multiplier">1.00×</strong><div class="flight-path"></div></div>';}
function betValue(){return Number($('#bet').value);}
function disableControls(disabled){$('#bet').disabled=disabled;$('#play').disabled=disabled;document.querySelectorAll('#extras input,#extras select').forEach(e=>e.disabled=disabled);}
function begin(bet){busy=true;state.balance=settle(state.balance,bet,0).balance;persist();renderBalance();disableControls(true);$('#result').textContent=t('playing');}
function finish(bet,multiplier){const payout=Math.round(bet*multiplier*100)/100;state.balance=Math.round((state.balance+payout)*100)/100;state.history.unshift({game:active.id,bet,payout,date:new Date().toISOString()});state.history=state.history.slice(0,100);persist();renderBalance();busy=false;disableControls(false);$('#play').onclick=playRound;$('#play').textContent=t('action')+' ↗';$('#result').className='result '+(payout>bet?'positive':payout===bet?'':'negative');$('#result').textContent=`${payout>bet?t('win'):payout===bet?t('push'):t('loss')} · ${fmt(payout)} CR · ${multiplier.toFixed(2)}×`;round=null;}
function playRound(){if(busy)return;const bet=betValue();if(!allowed(bet))return;begin(bet);
 if(active.id==='slots'){const symbols=['🍒','✦','💎','🔔','7'];let ticks=0;timer=setInterval(()=>{$('#stage').innerHTML=`<div class="reels">${Array.from({length:3},()=>`<span>${symbols[randomInt(5)]}</span>`).join('')}</div>`;if(++ticks===12){clearInterval(timer);const result=Array.from({length:3},()=>symbols[randomInt(5)]);$('#stage').innerHTML=`<div class="reels">${result.map(s=>`<span>${s}</span>`).join('')}</div>`;finish(bet,slotMultiplier(result));}},70);}
 if(active.id==='roulette'){const choice=$('#choice').value;$('.roulette-wheel').classList.add('spinning');setTimeout(()=>{const n=randomInt(37);$('.roulette-wheel').classList.remove('spinning');$('#roulette-number').textContent=n;$('#roulette-number').style.background=n===0?'#168d64':RED.has(n)?'#b82845':'#181820';finish(bet,rouletteMultiplier(n,choice));},1200);}
 if(active.id==='dice'){const threshold=Number($('#threshold').value);setTimeout(()=>{const n=randomInt(100);$('#dice-number').textContent=n;finish(bet,diceMultiplier(n,threshold));},500);}
 if(active.id==='mines'){const mineSet=new Set();while(mineSet.size<3)mineSet.add(randomInt(25));round={bet,mines:mineSet,safe:new Set()};$('#play').disabled=false;$('#play').textContent=t('cashout')+' · 1.00×';$('#play').onclick=()=>{if(round){revealMines();finish(bet,mineMultiplier(round.safe.size));}};document.querySelectorAll('[data-tile]').forEach(b=>{b.disabled=false;b.className='';b.textContent='◆';b.onclick=()=>{if(!round)return;const i=Number(b.dataset.tile);if(round.safe.has(i))return;b.disabled=true;if(round.mines.has(i)){revealMines();finish(bet,0);}else{round.safe.add(i);b.textContent='💎';b.classList.add('safe');$('#play').textContent=t('cashout')+` · ${mineMultiplier(round.safe.size).toFixed(2)}×`;if(round.safe.size===22){revealMines();finish(bet,mineMultiplier(22));}}};});}
 if(active.id==='blackjack'){const deck=shuffledDeck();round={bet,deck,player:[deck.pop(),deck.pop()],dealer:[deck.pop(),deck.pop()]};$('#extras').insertAdjacentHTML('beforeend',`<div id="bj-actions"><button class="outline" id="hit">${t('hit')}</button><button class="outline" id="stand">${t('stand')}</button></div>`);drawHands(false);$('#hit').onclick=()=>{if(!round)return;round.player.push(round.deck.pop());drawHands(false);if(blackjackScore(round.player)>=21)endBlackjack();};$('#stand').onclick=endBlackjack;if(blackjackScore(round.player)===21)endBlackjack();}
 if(active.id==='crash'){const u=(randomInt(1000000)+1)/1000001;const point=Math.min(20,Math.max(1,Math.floor(0.97/u*100)/100));round={bet,value:1};$('#multiplier').textContent='1.00×';$('#play').disabled=false;$('#play').textContent=t('cashout');$('#play').onclick=()=>{if(round){clearInterval(timer);finish(bet,round.value);}};const started=performance.now();timer=setInterval(()=>{if(!round){clearInterval(timer);return;}round.value=Math.min(20,Math.exp((performance.now()-started)/6500));$('#multiplier').textContent=round.value.toFixed(2)+'×';if(round.value>=point){clearInterval(timer);$('#multiplier').textContent=point.toFixed(2)+'× ✕';finish(bet,point===20?20:0);}},50);}
}
function revealMines(){document.querySelectorAll('[data-tile]').forEach(b=>{b.disabled=true;if(round.mines.has(Number(b.dataset.tile))){b.textContent='✹';b.classList.add('mine');}});}
function card(c){const rank={1:'A',11:'J',12:'Q',13:'K'}[c.rank]||c.rank;return `<div class="playing-card ${['♥','♦'].includes(c.suit)?'red-card':''}">${rank}<span>${c.suit}</span></div>`;}
function drawHands(reveal){$('#stage').innerHTML=`<div class="hand-label">${t('dealer')} ${reveal?'· '+blackjackScore(round.dealer):''}</div><div class="hand">${round.dealer.map((c,i)=>i===1&&!reveal?'<div class="playing-card card-back">M</div>':card(c)).join('')}</div><div class="hand-label">${t('you')} · ${blackjackScore(round.player)}</div><div class="hand">${round.player.map(card).join('')}</div>`;}
function endBlackjack(){if(!round)return;while(blackjackScore(round.player)<=21&&blackjackScore(round.dealer)<17)round.dealer.push(round.deck.pop());drawHands(true);const mult=blackjackMultiplier(round.player,round.dealer),bet=round.bet;$('#bj-actions')?.remove();finish(bet,mult);}
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue='';}});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'&&$('#search')){e.preventDefault();$('#search').focus();}});
render();

function publicProviderMarkup(){return `<div class="section-heading"><div><div class="eyebrow muted">OFFICIAL PROVIDER DEMOS</div><h2>${t('providerTitle')}</h2><p>${t('providerNote')}</p></div><button class="outline" id="provider-all">${t('providers')} ↗</button></div><div class="game-grid">${publicDemos.slice(0,page==='providers'?7:3).map(g=>`<article class="game-card"><div class="game-art ${g.art}"><span class="game-tag">PRAGMATIC PLAY · DEMO</span><div class="art-symbol">${g.icon}</div><div class="art-title">${esc(g.name)}</div><a class="play-overlay" href="${g.url}" target="_blank" rel="noopener noreferrer">${t('officialDemo')} ↗</a></div><div class="game-meta"><div><h3>${esc(g.name)}</h3><p>PRAGMATIC PLAY</p></div><a class="provider-link" href="${g.url}" target="_blank" rel="noopener noreferrer" aria-label="${g.name} ${t('officialDemo')}">↗</a></div></article>`).join('')}</div>`;}
function bindPublicProviders(){const b=$('#provider-all');if(b)b.onclick=()=>{page='providers';render();};}
async function renderProviders(){const content=$('#content');content.innerHTML=`<div class="page-heading"><div class="eyebrow">PROVIDER HUB</div><h1>${t('providers')}</h1><p>${t('providerRules')}</p></div><section class="provider-section">${publicProviderMarkup()}</section><section class="panel"><h2>${t('embedded')}</h2><p id="provider-status">${t('connecting')}</p><div id="provider-catalog"></div><div class="provider-direct"><a href="https://www.hacksawgaming.com/games" target="_blank" rel="noopener noreferrer">Hacksaw Gaming · ${t('officialDemo')} ↗</a><a href="https://www.pragmaticplay.com/en/games/?type=demo" target="_blank" rel="noopener noreferrer">Pragmatic Play · ${t('all')} ↗</a></div></section>`;bindPublicProviders();
 try{const status=await fetch('/api/providers/status').then(r=>r.ok?r.json():Promise.reject());if(page!=='providers')return;if(!status.configured){$('#provider-status').textContent=t('needsKeys');return;}
 const res=await fetch('/api/providers/games');if(!res.ok)throw new Error();const data=await res.json();if(page!=='providers')return;$('#provider-status').textContent=`${data.games.length} ${t('games')} · SoftAggregator · DEMO`;
 const providers=[...new Set(data.games.map(g=>g.provider))].sort();const categories=[...new Set(data.games.map(g=>g.category))].sort();
 $('#provider-catalog').innerHTML=`<div class="catalog-tools"><label class="search">⌕ <input id="provider-search" placeholder="${t('search')}" aria-label="${t('search')}"></label><label>${t('providerCount')}<select id="provider-filter"><option value="">${t('all')}</option>${providers.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('')}</select></label><label>${t('game')}<select id="category-filter"><option value="">${t('all')}</option>${categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label></div><div id="provider-list" class="provider-list"></div><div class="catalog-pagination"><button class="outline" id="catalog-prev">← ${t('prev')}</button><span id="catalog-page"></span><button class="outline" id="catalog-next">${t('next')} →</button></div>`;
 let currentPage=0,filtered=[];const pageSize=36;const byId=new Map(data.games.map(g=>[g.id,g]));
 const draw=()=>{const q=$('#provider-search').value.toLowerCase(),provider=$('#provider-filter').value,category=$('#category-filter').value;filtered=data.games.filter(g=>(g.name+' '+g.provider).toLowerCase().includes(q)&&(!provider||g.provider===provider)&&(!category||g.category===category));const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));currentPage=Math.min(currentPage,totalPages-1);const slice=filtered.slice(currentPage*pageSize,(currentPage+1)*pageSize);$('#provider-list').innerHTML=slice.map(g=>`<button data-launch="${esc(g.id)}">${g.image?`<img src="${esc(g.image)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:'<div class="catalog-placeholder">✦</div>'}<b>${esc(g.name)}</b><small>${esc(g.provider)}</small><span>▶ DEMO</span></button>`).join('')||`<p>${t('noResults')}</p>`;$('#catalog-page').textContent=`${currentPage+1} / ${totalPages} · ${fmt(filtered.length)} ${t('loadingMore')}`;$('#catalog-prev').disabled=currentPage===0;$('#catalog-next').disabled=currentPage>=totalPages-1;document.querySelectorAll('[data-launch]').forEach(b=>b.onclick=()=>launchProvider(b.dataset.launch,byId.get(b.dataset.launch)));};
 for(const selector of ['#provider-search','#provider-filter','#category-filter'])$(selector).addEventListener(selector==='#provider-search'?'input':'change',()=>{currentPage=0;draw();});$('#catalog-prev').onclick=()=>{currentPage--;draw();};$('#catalog-next').onclick=()=>{currentPage++;draw();};draw();
 }catch{if(page==='providers'&&$('#provider-status'))$('#provider-status').textContent=t('unavailable');}
}
async function launchProvider(id,game){if(state.pauseUntil>Date.now())return toast(t('paused'));const d=$('#modal');d.innerHTML=`<div class="modal-head"><div><span class="eyebrow">${esc(game.provider)} · DEMO</span><h2>${esc(game.name)}</h2></div><button id="close-provider" aria-label="${t('close')}">×</button></div><p id="launch-status">${t('connecting')}</p><div id="provider-frame"></div>`;d.oncancel=null;$('#close-provider').onclick=()=>d.close();d.showModal();
 try{const res=await fetch('/api/providers/launch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,device:innerWidth<768?'mobile':'desktop'})});if(!res.ok)throw new Error();const data=await res.json();const url=new URL(data.url);if(url.protocol!=='https:')throw new Error();if(!d.open||!$('#launch-status'))return;$('#launch-status').textContent=t('providerRules');const link=document.createElement('a');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';link.className='outline';link.textContent=t('officialDemo')+' ↗';$('#provider-frame').append(link);const frame=document.createElement('iframe');frame.src=url.href;frame.title=game.name+' demo';frame.allow='fullscreen';frame.referrerPolicy='no-referrer';frame.sandbox='allow-scripts allow-same-origin allow-forms allow-popups';$('#provider-frame').append(frame);
 }catch{if($('#launch-status'))$('#launch-status').textContent=t('unavailable');}
}
